### PR TITLE
cythonizing forward

### PR DESCRIPTION
**Pull request by fgregg**
Wanted to share this with you to get a sense of the opportunities for speedup. This is not something you probably want to merge.

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     4391    0.718    0.000   58.747    0.013 pyhacrf.py:124(predict_proba)
     4391    0.255    0.000   52.379    0.012 pyhacrf.py:326(__init__)
     4391   33.744    0.008   52.124    0.012 pyhacrf.py:385(_build_lattice)
     4390    0.045    0.000    5.565    0.001 pyhacrf.py:356(predict)
     4390    0.122    0.000    5.267    0.001 pyhacrf.py:362(_forward_probabilities)
     4390    0.007    0.000    5.142    0.001 pyhacrf.py:376(_forward)
     4390    5.134    0.001    5.134    0.001 {pyhacrf.algorithms.forward}
     4391    0.005    0.000    3.314    0.001 pyhacrf.py:275(fit_transform)
     4391    0.008    0.000    3.309    0.001 pyhacrf.py:291(transform)
     4391    2.506    0.001    3.302    0.001 pyhacrf.py:307(_extract_features)
```

If we changed alpha from a dict to a numpy array. 

```
     3059    0.324    0.000   41.912    0.014 pyhacrf.py:124(predict_proba)
     3059    0.217    0.000   40.386    0.013 pyhacrf.py:326(__init__)
     3059   25.773    0.008   40.169    0.013 pyhacrf.py:385(_build_lattice)
     3059    0.005    0.000    2.604    0.001 pyhacrf.py:275(fit_transform)
     3059    0.007    0.000    2.599    0.001 pyhacrf.py:291(transform)
     3059    1.958    0.001    2.592    0.001 pyhacrf.py:307(_extract_features)
     3058    0.046    0.000    1.130    0.000 pyhacrf.py:356(predict)
     3058    0.112    0.000    0.881    0.000 pyhacrf.py:362(_forward_probabilities)
     3058    0.006    0.000    0.766    0.000 pyhacrf.py:376(_forward)
     3058    0.759    0.000    0.759    0.000 {pyhacrf.algorithms.forward}
```

### CODE REVIEW

**Comment by fgregg** [comment]
In the pure prediction case, we don't need to track 'edge nodes' so, alpha can just be a 

```
cdef np.ndarray(double, ndim=3) alpha = numpy.empty_like(x_dot_parameters)
alpha.fill(-np.inf)
```

**Comment by fgregg** [comment]
We only need another 10x speed improvement, then this will be usable in dedupe. Very exciting!

**Comment by dirko** [comment]
Thanks Forest, this is wonderful!

Since I don't have much experience optimizing python like this, can you maybe explain why the first change works?

**Comment by fgregg** [comment]
So if cython knows the variable type for variables, it can compile more of the code to C. Because numpy.arrays are already typed, cython can make fast C code out of anything that uses them, if you fully declare what types of variables the array will contain.

Using the dictionary slows the code down, because python dictionaries can contain a heterogeneous mix of variable types. Cython actually calls cPython for getting and settings of dict variables.

Finally, cython has some pure C versions of numpy.math functions, which is what I'm getting by doing `numpy.math cimport logaddexp`

A **really** useful tool for optimizing cython is the cython annotation mode: http://docs.cython.org/src/quickstart/cythonize.html#determining-where-to-add-types

**Comment by dirko** [comment]
Thanks that is very helpful, especially the `-a` switch.

**Comment by dirko** [comment]
@fgregg I should have tested this before merging, but I can't build the project now using `python setyp.py build_ext --inplace`. Guess it has something to do with https://github.com/datamade/pyhacrf/commit/e187a21b0a01e1a38e36c0b2f9e7887a5e5299d9#diff-2eeaed663bd0d25b7e608891384b7298R7 but the link seems to be broken. How are you building?

**Comment by fgregg** [comment]
Run 'cython pyhacrf/algorithms.pyx' the run build_ext

**Comment by fgregg** [comment]
To expand on that a little bit, I hacked this up because I wasn't sure how to pass the npymath library arguments to cythonize (that's what `**get_info('npymath')`) is doing, but I knew how to pass the argument as an extension.

That said, I do use the pattern in my cython/numpy for the following reasons.
- Cython is a heavy dependency. I build the c files myself when I'm ready to make a distribution release and they will be included with `python setup.py sdist.` 
- I try to avoid numpy as a top level dependency of the setup.py file. If the user doesn't have numpy, then python can't read the rest of the setup.py file and provide useful informatoin to the user. The whole point of `NumpyExtension` is to encapsulate the numpy dependency so all users can run setup.py. 

But, like I said this setup.py is a little hacked up right now. This is kinda what it is supposed to look like: https://github.com/datamade/affinegap/blob/master/setup.py

Whether you want to use this pattern is, of course, up to you. I'm sure there's a way to pass the relevant arguments to cythonize.

**Comment by dirko** [comment]
Seems reasonable - I'll just add something on the readme.

When I now first run `cython pyhacrf/algorithms.pyx` I get:

```
Error compiling Cython file:
------------------------------------------------------------
...
            i0, j0, s0, i1, j1, s1, edge_parameter_index = node  # Actually an edge in this case
            # Use the features at the destination of the edge.
            edge_potential = (x_dot_parameters[i1, j1, edge_parameter_index]
                              + alpha[(i0, j0, s0)])
            alpha[node] = edge_potential
            alpha[(i1, j1, s1)] = logaddexp(alpha.get((i1, j1, s1), -np.inf),
                                          ^
pyhacrf/algorithms.pyx:27:43: Call with wrong number of arguments (expected 1, got 2)
```

Something to do with the `numpy` version maybe?

When I change `logaddexp(...)` to `logaddexp((...))` the `cython` command completes successfully but  `setup.py build_ext` returns:

```
pyhacrf/algorithms.c:1762:62: error: too few arguments to function call, expected 2, have 1
      __pyx_t_6 = PyFloat_FromDouble(npy_logaddexp(__pyx_t_27)); if (unlikely(!__pyx_t_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                     ~~~~~~~~~~~~~           ^
~/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:305:1: note: 'npy_logaddexp' declared here
double npy_logaddexp(double x, double y);
^
1 warning and 1 error generated.
```

Any ideas?

**Comment by fgregg** [comment]
There was a bug in cython that was fixed in cytho 22.

**Pull request merged**
