### PR TITLE
[WIP] Precalculate lattice

### PR DESCRIPTION
**Pull request by fgregg**
Precalculating the independent parts of the lattice gets this speed where we need to be. This PR is not ready to merge yet.

### CODE REVIEW

**Comment by fgregg** [comment]
@dirko this is very close

I have it all but 4 tests. There's some obscure bug I can't quite find.

In order take advantage of precomputing the lattice, I needed a homogenous way of representing the lattice, so I decided to represent it as a edgelist. This actually makes some other things much faster, but it means I had to touch a lot of code. 

I'd appreciate it if you could look at the forward algorithm, the backward algorithm, and the forward_backward. 

Thanks!

**Comment by fgregg** [comment]
down to three test. Please take a look.

**Comment by fgregg** [comment]
So one of the failures was failing before (`test_fit_predict`).

The other two tests are tests of derivates. Strangely, the value of the actual derivates has not changed, but the the value of the "expected derivates" in these tests has changed.

**Comment by fgregg** [comment]
@dirko, all test's passing now!!! ready to merge.

**Comment by fgregg** [comment]
@dirko, after you merge this, and are satisfied could you run compile the pyx files to c and upload a distribution to pypi. I want to synch this into dedupe, and need this on pypi.

**Comment by dirko** [comment]
Sorry I haven't come around to look at this yet - will try to go through it as soon as possible - but as you said it's a large change!

**Comment by fgregg** [comment]
Sorry, it is pretty big. Happy to chat about on IRC or google voice.

**Comment by dirko** [comment]
I'll organise the `StateMachine`s a bit differently. 

The public and private methods and members must be differentiated, for example `_build_lattice` is the only public method but is prepended with an underscore, while `independent_lattice`, `grow_dependent_lattice` etc should be private helpers.

I think that `DefaultStateMachine` and `GeneralStateMachine` should be two different classes. They can inherit from a base class that implements `build_lattice`, `states_to_classes`, and `n_states` (or can implement these members and methods with duck-typing). At the moment the `StateMachine` interface is a bit confusing I think.

I also think the constructions of the `TestStateMachine`s with class variables is unnecessary - why don't we rather pass the `transitions`, `start_states` etc as parameters to the constructor? This will make testing easier.

For now I'll merge and then implemented these changes - let me know if this again messes with the running speed!

**Comment by fgregg** [comment]
Good points! Sounds like a plan

**Pull request merged**
