### PR TITLE
Speed up feature extraction by using numpy feature extractions

### PR DESCRIPTION
**Pull request by fgregg**
Hey @dirko, what do you think about this approach. It's still pretty clear what's going on and it's much much faster.

### CODE REVIEW

**Comment by dirko** [comment]
Giving the choice of how to vectorise the feature generation to the user makes a lot of sense to me. So as I understand it each binary feature function must return a slice through the final three dimensional ndarray. Can you maybe just document this new API [here](https://github.com/dirko/pyhacrf/pull/15/files#diff-1f8ce8304aae25d7525d6f80e521d843R43) - then I'll merge. Thanks!

**Comment by fgregg** [comment]
Sorry. Where do you want the documentation?

**Comment by dirko** [comment]
Ah it seems that the line number disappeared - Line 43 of `feature_extraction.py`.

**Comment by fgregg** [comment]
How does that look?

**Comment by dirko** [comment]
Great!

**Pull request merged**
