### PR TITLE
named function for pickling

### PR DESCRIPTION
**Pull request by fgregg**
hi @dirko, 

This replaces an anonymous function with a named function, which is necessary for pickling the feature extractor. 

Could you please merge this and release a new version to pypi. Thanks!

### CODE REVIEW

**Comment by dirko** [comment]
Cool - are you using the character features? How are they working for you? 

I had some trouble getting them to give better results on testing data (there are just too many parameters - I'm therefore thinking about removing some of the parameters, or at least giving the option of removing them when using the character features.)

**Comment by fgregg** [comment]
Hi @dirko, could you make a release. Have a few things waiting for that. 

I haven't tried using the character features. It is a _lot_ of features. What about starting by making them symmetric? That would cut them in half.

**Comment by dirko** [comment]
Good idea!

(Unfortunately I can't release now but will in a few hours)

**Comment by dirko** [comment]
[Released]

**Pull request merged**
